print('Today is a good day!')
print(1+1)
print('1+1')
print("J'ai appris la fonction d'impression aujourd'hui.")
print(24*56)
print("J'aime les pommes,il aime les poires.")
print("J'aime les pommes,")
print('il aime les poires.')
print("j'aime les pommes,\nil aime les poires.")
